<?php

/**
 * @file
 * fintranet_common.module
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_file_download().
 */
function fintranet_common_file_download($uri) {
  $filename = \Drupal::service('file_system')->basename($uri);
  $disposition = 'attachment; filename="' . $filename . '"';
  return [
    'Content-disposition' => $disposition,
  ];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function fintranet_common_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Attach CSS library to all node add/edit forms.
  $form['#attached']['library'][] = 'fintranet_common/node-form';
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function fintranet_common_form_media_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Attach CSS library to all media add/edit forms.
  $form['#attached']['library'][] = 'fintranet_common/node-form';
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function fintranet_common_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Hide the relations detail in all taxonomy forms.
  $form['relations']['#attributes']['class'][] = 'visually-hidden';

  switch ($form_id) {
    case 'taxonomy_term_organization_form':
      // Change term name label to vocabulary acronym e.g. Organization acronym.
      $taxonomy_vocabulary = ucfirst($form['vid']['#value']);
      $form['name']['widget'][0]['value']['#title'] = $taxonomy_vocabulary . " acronym";
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function fintranet_common_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $block_forms = [
    'block_content_content_form',
    'block_content_basic_edit_form',
  ];
  if (in_array($form_id, $block_forms)) {
    // Attach CSS library to all block add/edit forms.
    $form['#attached']['library'][] = 'fintranet_common/node-form';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function fintranet_common_form_media_library_add_form_upload_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Hide Add file field for media types in CKEditor Media Library modal.
  $storage = &$form_state->getStorage();
  $selected_media_type = $storage['media_library_state']->getSelectedTypeId();
  $media_types = [
    'form',
    'gallery',
  ];
  if (in_array($selected_media_type, $media_types)) {
    $form['#attributes']['class'][] = 'visually-hidden';
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function fintranet_common_menu_local_tasks_alter(&$data, $route_name) {
  $admin_content_route = [
    'system.admin_content',
    'view.fintranet_admin_content.page_3',
    'view.fintranet_admin_content.page_4',
    'view.fintranet_admin_content.page_5',
    'view.fintranet_admin_content.page_6',
    'view.fintranet_admin_content.page_7',
    'view.fintranet_admin_content.page_8',
    'view.fintranet_admin_content.page_9',
    'view.fintranet_admin_content.page_10',
    'view.fintranet_admin_content.page_11',
  ];
  if (in_array($route_name, $admin_content_route)) {
    // Remove default primary tabs from system.admin_content.
    unset($data['tabs'][0]['entity.block_content.collection']);
    unset($data['tabs'][0]['comment.admin']);
    unset($data['tabs'][0]['entity.media.collection']);
    unset($data['tabs'][0]['views_view:view.files.page_1']);
    unset($data['tabs'][0]['poll.poll_overview']);
    unset($data['tabs'][0]['views_view:view.block_content.page_1']);
    unset($data['tabs'][0]['views_view:view.media.media_page_list']);
    // Remove default secondary tabs from system.admin_content.
    unset($data['tabs'][1]);
  }
}

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function fintranet_common_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  $view_id = [
    'fintranet_admin_content',
    'fintranet_admin_content_block',
    'fintranet_admin_media',
    'media_library',
  ];

  if (in_array($form_state->get('view')->id(), $view_id)) {
    // Attach CSS file to fix margin issues for CSHS.
    $form['#attached']['library'][] = 'fintranet_common/cshs';
    // Clean up the appearance of the autocomplete Author field.
    $form['author']['#size'] = 20;
    unset($form['author']['#description']);
  }
}
