<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_preprocess_HOOK() for input__submit.html.twig.
 */
function bcbb_search_preprocess_input__submit(array &$variables): void {
  // Give danger classes to site search Reset button.
  if ($variables['attributes']['id'] === 'edit-reset-site-search') {
    $variables['attributes']['class'][] = 'button--danger';
    $variables['attributes']['class'][] = 'icon-bi-trash3';
  }
}
