<?php

namespace Drupal\bc_dc\Service;

use Drupal\bc_dc\Traits\ReviewReminderTrait;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\DependencyInjection\ContainerInjectionInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Logger\LoggerChannelFactoryInterface;
use Drupal\Core\Logger\LoggerChannelTrait;
use Drupal\Core\StringTranslation\StringTranslationTrait;
use Drupal\Core\StringTranslation\TranslationInterface;
use Drupal\Core\Url;
use Drupal\message_gcnotify\Service\GcNotifyApiService;
use Drupal\node\NodeInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Service for sending reminders to review out-of-date data_set nodes.
 */
class EmailSending implements ContainerInjectionInterface {

  use LoggerChannelTrait;
  use ReviewReminderTrait;
  use StringTranslationTrait;

  /**
   * Constructs a new EmailSending object.
   *
   * @param \Drupal\Core\Config\ConfigFactoryInterface $configFactory
   *   The config.factory service.
   * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager
   *   The entity_type.manager service.
   * @param \Drupal\Core\Logger\LoggerChannelFactoryInterface $loggerFactory
   *   The logger.factory service.
   * @param \Drupal\Core\StringTranslation\TranslationInterface $stringTranslation
   *   The string_translation service.
   */
  public function __construct(
    protected ConfigFactoryInterface $configFactory,
    protected EntityTypeManagerInterface $entityTypeManager,
    LoggerChannelFactoryInterface $loggerFactory,
    TranslationInterface $stringTranslation,
  ) {
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('config.factory'),
      $container->get('entity_type.manager'),
      $container->get('logger.factory'),
      $container->get('string_translation'),
    );
  }

  /**
   * Get and send review reminders to all data_set authors.
   */
  public function sendRemindersToAllUsers(): void {
    $assets_needing_review = $this->getAssetsNeedingReview();
    foreach ($assets_needing_review as $uid => $assets_needing_review_for_user) {
      $this->sendRemindersToOneUser($uid, $assets_needing_review_for_user);
    }
  }

  /**
   * Send an review reminder to a data_set author.
   *
   * @param int $uid
   *   The UID of the user to send the message to.
   * @param array $assets_needing_review_for_user
   *   An array of this user's assets that need review, as generated by ::getAssetsNeedingReview().
   *
   * @return bool|null
   *   TRUE if sending succeed, FALSE if it failed, NULL if the user has no
   *   email address or if there are no updates to send to this user.
   */
  public function sendRemindersToOneUser(int $uid, array $assets_needing_review_for_user): ?bool {
    $account = $this->entityTypeManager->getStorage('user')->load($uid);
    $email = $account?->getEmail();
    $logger = $this->getLogger('bc_dc');

    if (!$email) {
      $logger->error('ReviewReminder: User @uid has no email address.', ['@uid' => $uid]);
      return NULL;
    }

    $body = $this->generateReviewReminderBody($assets_needing_review_for_user, $uid);
    if (!$body) {
      $logger->error('ReviewReminder: Empty message for user @uid.', ['@uid' => $uid]);
      return NULL;
    }

    $subject = $this->t('Metadata records you maintain need updates', [], ['langcode' => $account->getPreferredLangcode()]);

    $success = GcNotifyApiService::sendMessage([$email], $subject, $body);
    if ($success) {
      $logger->notice('Sent ReviewReminder message to user @uid.', ['@uid' => $uid]);
    }
    else {
      $logger->error('Failed to send ReviewReminder message to user @uid.', ['@uid' => $uid]);
    }

    return $success;
  }

  /**
   * Generate the body of a review reminder message to a data_set author.
   *
   * @param array $assets_needing_review_for_user
   *   An array of assets that need review, one user's worth of what is
   *   generated by ::getAssetsNeedingReview().
   * @param int $uid
   *   User ID of user that these assets belong to.
   *
   * @return string|null
   *   The body of the message or NULL if there is no message to send.
   */
  public function generateReviewReminderBody(array $assets_needing_review_for_user, $uid): ?string {

    $user = $this->entityTypeManager->getStorage('user')->load($uid);

    $update_types = [
      static::REVIEW_OVERDUE,
      static::REVIEW_NEEDED,
    ];
    $body_records_to_review = '';
    $count_records_to_review = 0;

    // First, loop through the records needing review, and
    // render the text for each one of them, to go in the email.
    foreach ($update_types as $update_type) {
      if (!empty($assets_needing_review_for_user[$update_type])) {
        foreach ($assets_needing_review_for_user[$update_type] as $asset_needing_review) {
          ++$count_records_to_review;

          // If a user clicks one of these links to one of
          // their Metadata Records in the email they receive,
          // they will confusingly get a "Not Found" error
          // if they are not logged in.
          // So we make the link to instead to the login page, with a REDIRECT
          // to the real URL we want to take them to.
          $url_via_login = Url::fromRoute('user.login', [], [
            'query' => ['destination' => '/node/' . $asset_needing_review->id()],
            'absolute' => TRUE,
          ]);
          $prev_review_date = strtotime($asset_needing_review->field_last_review_date->value);
          $review_freq_months = $asset_needing_review->field_review_interval->value;

          // Calculate $next_review_date.
          [$y, $m, $d] = explode(' ', date('Y m d', $prev_review_date));
          $m += $review_freq_months;
          $next_review_date = (new \DateTime())->setDate($y, $m, $d)->format('U');

          $date_formatter = \Drupal::service('date.formatter');

          // GC Notify requires Markdown formatting, not HTML.
          $body_records_to_review .= t(<<<END_RECORD_TO_REVIEW
[@asset_title](@url_via_login) @review_is_overdue
* Last Reviewed: @prev_review_date
* Review Frequency: @review_freq
* Next Review Due: @next_review_date (@next_review_ago_or_fromnow)


END_RECORD_TO_REVIEW,
            [
              '@asset_title'       => $asset_needing_review->getTitle(),
              '@url_via_login'     => $url_via_login->toString(),
              '@review_is_overdue' => $update_type == static::REVIEW_OVERDUE
                ? '(review of this record is **overdue**)'
                : '',
              '@prev_review_date' => date('F j, Y', $prev_review_date),
              '@review_freq'      => $review_freq_months == 12
                ? 'Annually'
                : $this->formatPlural($review_freq_months, 'Every month', 'Every @count months'),
              '@next_review_ago_or_fromnow' => time() > $next_review_date
                ? $date_formatter->formatTimeDiffSince($next_review_date) . ' overdue'
                : $date_formatter->formatTimeDiffUntil($next_review_date) . ' from now',
              '@next_review_date' => date('F j, Y', $next_review_date),
            ]
          );
        }
      }
    }

    // Now add on the header and footer.
    $body = t(<<<END_BODY
Dear @first_name,

To uphold the trust of our users in the Data Catalogue, it is important that the records are reviewed periodically. Your attention to this ensures the accuracy and reliability of the data we maintain.

Please review the following @count_records:


@records_to_review

___

@email_footer

END_BODY,
      [
        '@first_name' => $user->field_first_name->value,
        '@count_records' => $this->formatPlural($count_records_to_review, 'record', '@count records'),
        '@records_to_review' => $body_records_to_review,
        '@email_footer' => $this->getEmailFooter(),
      ]
    );

    return $body;
  }

  /**
   * Generate an array of data_set node update notification data.
   *
   * The array includes the title and URL and is grouped by author and review
   * status (needed or overdue):
   * @code
   * return [
   *   UID => [
   *     static::REVIEW_OVERDUE => [
   *       ['title' => STRING, 'url' => STRING],
   *       ...
   *     ],
   *     static::REVIEW_NEEDED => [...],
   *   ],
   *   ...
   * ];
   * @endcode
   *
   * @return array
   *   The array of data_set node update notification data.
   */
  public function getAssetsNeedingReview(): array {
    $node_storage = $this->entityTypeManager->getStorage('node');

    $query = $node_storage->getQuery()
      ->accessCheck(FALSE)
      ->condition('type', 'data_set')
      ->exists('field_review_interval')
      ->exists('field_last_review_date');
    $data_set_nids = $query->execute();

    $assets_needing_review = [];

    foreach ($data_set_nids as $data_set_nid) {
      $data_set = $node_storage->load($data_set_nid);
      $review_status = static::dataSetReviewNeeded($data_set);
      if ($review_status) {
        $assets_needing_review[$data_set->getOwnerId()][$review_status][] = $data_set;
      }
    }

    return $assets_needing_review;
  }


  /**
   * Get the common text we put in email footers.
   */
  public function getEmailFooter() {
    $is_test_or_dev = preg_match('/(dev|test)/i', \Drupal::config('environment_indicator.indicator')->get('name') ?? '');

    return t(<<<END_EMAIL_FOOTER
  For more information or assistance, please @contact_us.

  Ministry of Finance Data Catalogue
  @data_cat_main_url
  END_EMAIL_FOOTER,
    [
      '@contact_us' => $is_test_or_dev
        ? 'contact Nicole.deGreef@gov.bc.ca'
        : 'reach out via [Finance Data Catalogue Support](https://fincsp.atlassian.net/servicedesk/customer/portal/12)',
      '@data_cat_main_url' => Url::fromRoute('<front>', [], ['absolute' => TRUE])->toString(),
    ]);
  }

  /**
   * Send an email to someone re a bookmarked data_set having been updated.
   *
   * @param \Drupal\user\Entity\User $owner
   *   User who bookmarked this Metadata record.
   * @param [type] $data_set
   *   The Metadata record they bookmarked.
   */
  function sendEmailReChangedMetadataRecord($owner, $data_set, $owner_last_viewed_mr_timestamp) {

    // We want to be able to say what kind of metadata record this is:
    // - Postgres database
    // - CHEFS form
    // etc.
    // To do this, we first look up the data-type term, and its ancestors.
    // Then we make a few changes (so that it reads better), and render it.
    //
    // Build an array of this data_set's type's term's name,
    // and its ancestors' names.
    // We are trying to build this var: $nice_record_type_name.
    /* e.g. Data -> File -> CSV.              => "CSV data-file"
    //      Data -> Database -> Postgres      => "Postgres database"
    //      Data -> Database                  => "Database"
    //      Form -> CHEFS                     => "CHEFS form"
    //      Report                            => "Report"
    //      Data                              => "Data-source"
    */
    $dataset_type_names = [];
    $dataset_type_tid = $data_set->field_data_set_type[0]->getValue()['target_id'];
    $term_ancestry = $this->entityTypeManager->getStorage('taxonomy_term')->loadAllParents($dataset_type_tid);
    foreach ($term_ancestry as $dataset_type_term) {
      $dataset_type_names[] = $dataset_type_term->getName();
    }

    // $term_ancestry looks like 0=>'Postgres', 1='Database', 2=>'Data'.
    // -- We want this reversed for our manipulations below.
    $dataset_type_names = array_reverse($dataset_type_names);

    if ($dataset_type_names[0] == 'Data') {
      // Rename 'File' to be clearer.
      if ($dataset_type_names[1] == 'File') {
        $dataset_type_names[1] = 'Data-file';
      }

      // Throw away the first 'Data' term. We'll just call it a
      // "Postgres database", not "Postgres database 'data'".
      array_shift($dataset_type_names);
    }

    $nice_record_type_name = isset($dataset_type_names[1])
      ? $dataset_type_names[1] . ' ' . strtolower($dataset_type_names[0])
      : $dataset_type_names[0];


    // Build up the list of links to show:
    //   - one to view the MR
    //   - one to view the *changes* to the MR
    //   - optional one to view all changes to the MR since the user last looked at it.
    $links_to_show = '';

    $link_to_view_dataset = Url::fromRoute('user.login', [], [
          'query' => ['destination' => '/node/' . $data_set->id()],
          'absolute' => TRUE,
        ])->toString();
    $links_to_show .= "- [The latest complete version of the record]($link_to_view_dataset)\n";

    // '$sr' is 'significant revisions'
    $sr = $this->getSignificantRevisions($data_set, $owner_last_viewed_mr_timestamp);

    $link_to_recent_change = $this->getSingleDiffLink($data_set->id(), 
      $sr['most_recent_published_rev'],
      $sr['current_published_rev']
    );
    $links_to_show .= "- [Only the changes that were just made]($link_to_recent_change)\n";
    
    if ($sr['most_recent_published_rev'] != $sr['most_recent_published_rev_user_has_seen']) {
      $link_to_changes_user_hasnt_seen = $this->getSingleDiffLink($data_set->id(), 
        $sr['most_recent_published_rev_user_has_seen'],
        $sr['current_published_rev']
      );
      if (date('Ymd', $owner_last_viewed_mr_timestamp) == date('Ymd')) {
        $when_last_viewed = 'today';
      }
      elseif (date('Ymd', $owner_last_viewed_mr_timestamp) == date('Ymd', time()-24*3600)) {
        $when_last_viewed = 'yesterday';
      }
      else {
        if (time() - $owner_last_viewed_mr_timestamp < 24*3600*30*8) {
          // Less than 8 months ago. Use just month and day  e.g. "January 23rd"
          $date_format = 'F jS';
        }else{
          // More than 8 months ago... use year, too.
          $date_format = 'F jS, Y';
        }
        $when_last_viewed = 'on ' . date($date_format, $owner_last_viewed_mr_timestamp); 
      }
      $links_to_show .= "- [All the changes that have been made since you last viewed this record, $when_last_viewed]"
        ."($link_to_changes_user_hasnt_seen)\n";
    }


    // This "remove-bookmark" link doesn't work, I think due to
    // the CSRF token being connected to the wrong user?
    /* $remove_bookmark_link = Url::fromRoute('flag.action_link_unflag',
    ['flag'=>'bookmark', 'entity_id'=> $data_set->id()],
    ['absolute' => TRUE])->toString(),
    */
    $orig_title = $data_set->original->getTitle();
    $cur_title = $data_set->getTitle();
    $possible_new_title = $orig_title == $cur_title 
      ? '' 
      : sprintf(' (whose title is now "%s")', $cur_title); 

    // Build the email!

    $subject = t('Update to "@asset_name" metadata record', ['@asset_name' => $orig_title]);

    $body_content = t(<<<END_BODY
Dear @first_name,

In the Finance Data Catalogue, you previously bookmarked the metadata record "[@asset_name](@asset_url)"@possible_new_title. 

This @nice_record_type_name has just been updated. Click to view:

@links_to_show

___

If you no longer want these reminders, you can unbookmark the related record here:

- ["My bookmarks", in the Finance Data Catalogue](@subscriber_alerts_url)


END_BODY,
      [
        '@first_name' => $owner->field_first_name->value,
        '@nice_record_type_name' => $nice_record_type_name,
        '@asset_name' => $orig_title,
        '@asset_url' => Url::fromRoute('user.login', [], [
          'query' => ['destination' => '/node/' . $data_set->id()],
          'absolute' => TRUE,
        ])->toString(),
        '@possible_new_title' => $possible_new_title,
        '@links_to_show' => $links_to_show,
        '@subscriber_alerts_url' => Url::fromRoute('user.login', [], [
          'query' => ['destination' => '/user/' . $owner->id() . '/bookmarks'],
          'absolute' => TRUE,
        ])->toString(),
      ]
    );

    $body_content .= $this->getEmailFooter();

    // Send the message and log the result.
    $success = GcNotifyApiService::sendMessage([$owner->getEmail()], $subject, $body_content);
    $logger = $this->getLogger('bc_dc');
    $logger->notice(($success ? 'Sent message' : 'Failed sending message')
              . ' to user @user_num when updating data_set @nid.', [
                '@user_num' => $owner->id(),
                '@nid' => $data_set->id(),
              ]
    );
  }


  /**
   * getSignificatnRevisions()
   * 
   * Given a MetadataRecord and the time that a person last viewed it,
   * return a list of the following revision IDs:
   *   - ID of currently published revision
   *   - ID of previously publishe revision
   *   - ID of the published revision that was active when the person last viewed it.
   *
   * @param NodeInterface $metadata_record
   * @param integer $since_timestamp
   * @return array
   */
  public function getSignificantRevisions(NodeInterface $metadata_record, int $since_timestamp) {
    $node_storage = $this->entityTypeManager->getStorage('node');
    $revision_ids = $node_storage->revisionIds($metadata_record);

    do {
      $current_rev_id = array_pop($revision_ids);
      if (!$current_rev_id) throw new \Exception("No published revisions for node $nid.");
    } while (
        $node_storage->loadRevision($current_rev_id)->moderation_state[0]->value != 'published'
    );

    $most_recent_published_rev_id = null;
    do {
      $this_rev_id = array_pop($revision_ids);
      if (!$this_rev_id) throw new \Exception("No previously published revisions for node {$metadata_record->id()}.");
      $this_rev = $node_storage->loadRevision($this_rev_id);
      if ($this_rev->moderation_state[0]->value == 'published') {
        $most_recent_published_rev_id = $most_recent_published_rev_id ?: $this_rev_id;
      }
      } while (
           $this_rev->moderation_state[0]->value != 'published'
        || $this_rev->revision_timestamp->value > $since_timestamp
    );
          
    return ([
      'current_published_rev'                   => $current_rev_id,
      'most_recent_published_rev'               => $most_recent_published_rev_id,
      'most_recent_published_rev_user_has_seen' => $this_rev_id,
    ]);

  }

  /**
   * getSingleDiffLink()
   * 
   * Build the URL needed to view a diff between two revisions of a Node.
   * e.g. https://test.cat.data.fin.gov.bc.ca/node/418/revisions/view/21080/21081/visual_inline
   * (That is the URL you end up at, but actually the URL sends you to the user login,
   * with a redirect to that URL.)
   *
   * @param integer $nid
   * @param integer $earlier_rev_id
   * @param integer $later_rev_id
   * @return String 
   */
  public function getSingleDiffLink(int $nid, int $earlier_rev_id, int $later_rev_id) {
    $diff_link = Url::fromRoute('diff.revisions_diff',
      [
        'node' => $nid,
        'left_revision' => $earlier_rev_id,
        'right_revision' => $later_rev_id,
        'filter' => 'visual_inline',
      ],
      ['absolute' => FALSE]
    )->toString();

    $diff_via_login = Url::fromRoute('user.login', 
      [], 
      [
        'query' => ['destination' => $diff_link],
        'absolute' => TRUE,
      ]
    )->toString();

    return $diff_via_login;
  }

}
