#!/bin/bash

echo
echo "Beginning backup of database and files..."

APP_NAME=$1
ENV_NAME=$2
DB_TYPE=$3

DRUPAL_ROOT="/var/www"
BACKUPS_DIR="/backup"
DAILY_BACKUPS_DIR="$BACKUPS_DIR/daily"
WEEKLY_BACKUPS_DIR="$BACKUPS_DIR/weekly"
MONTHLY_BACKUPS_DIR="$BACKUPS_DIR/monthly"

PRIVATE_FILES_PATH="$DRUPAL_ROOT/private"
PUBLIC_FILES_PATH="$DRUPAL_ROOT/html/sites/default/files"

BUILD_HASH_FILE="$DRUPAL_ROOT/build-hash.txt"

# Directory should already be mounted. Test that it is there.
if [ ! -d $BACKUPS_DIR ]; then
  echo "About to do backups, but backup dir '$BACKUPS_DIR' doesn't exist!"
  exit 1;
fi

# The files we commit to git can't extend onto the backups dir,
# as it is not mounted at deploy-time. So, rather than committing a
# readme file in the backups dir, we generate it here:
cat > $BACKUPS_DIR/README.txt <<- END_OF_README
	These backups (and this README) are managed by openshift-based cronjobs.
	See:
	  - $DRUPAL_ROOT/scripts

  In tenant-gitops repo, see:
    - helm-drupal/charts/drupal/conf/drupal-cron-backup.bash
	  - helm-drupal/charts/drupal/templates/cronjob/drupal-backup.yaml

	The backups directory itself is mounted as type 'netapp-file-backup',
	which means that OCIO will be managing backups of this directory for us.

	See https://github.com/BCDevOps/backup-container?tab=readme-ov-file#backup-storage-volume
END_OF_README

# Set up the 'backup descriptor'. This will be used for each of:
#   * the directory name, for this backup.
#          (this directory will also contain the 'public/private-files' backups)
#           e.g. "2024-05-02.UTC.11h30.newbbproj-dev"
#   * the DB dump file.
#           e.g. "DB_DUMP.2024-05-02.UTC.11h30.newbbproj-dev.SQL.GZ"
COMMIT_HASH=$(cat $BUILD_HASH_FILE | cut -c 1-8)
TIME_AND_DATE=$(date +"%F.UTC.%Hh%M")
BACKUP_DESCRIPTOR=$TIME_AND_DATE.${APP_NAME}-${ENV_NAME}.commit-${COMMIT_HASH}

# Get previous backup dir,
#   as a reference to make hard-links against during rsync, below.
#      find: gets all directories in the 'daily' dir,
#                 which look like our backup dir name, to exclude any special directories (e.g. ".git") that we might someday add.
#      xargs ls -td1:  Sort them by date, newest to oldest.
#      head -n1: Grab the newest one off the top.
MOST_RECENT_BACKUP_DIR=$(ls -dt1  $DAILY_BACKUPS_DIR/*.UTC.* | head -n1 )
# If there are no backups, this will return "." rather than nothing. Fix this.
if [[ $MOST_RECENT_BACKUP_DIR == "." ]]; then MOST_RECENT_BACKUP_DIR=""; fi

# Create the dir for this backup.
THIS_BACKUP_DIR="$DAILY_BACKUPS_DIR/$BACKUP_DESCRIPTOR"
echo "Creating new backup directory: $THIS_BACKUP_DIR"
mkdir -p $THIS_BACKUP_DIR

# Do the database dump
DB_OUTPUT_FILENAME=DB_DUMP.$BACKUP_DESCRIPTOR.sql.GZ
echo "Dumping database to file '$DB_OUTPUT_FILENAME' ..."
NO_CACHE_DATA="--structure-tables-list=cache,cache_*"
if [[ $DB_TYPE == 'mysql' ]]; then
  SQL_EXTRA_FLAGS="--no-tablespaces --skip-ssl-verify-server-cert"
    # '--no-tablespaces' is to address this error that was coming up:
    #   "Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces"
    # '--skip-ssl-verify-server-cert' is to get around an SSL problem (see ticket EE-275)
  drush sql:dump $NO_CACHE_DATA --extra-dump="$SQL_EXTRA_FLAGS" -vvv | gzip > $THIS_BACKUP_DIR/$DB_OUTPUT_FILENAME
else
  drush sql:dump $NO_CACHE_DATA                                 -vvv | gzip > $THIS_BACKUP_DIR/$DB_OUTPUT_FILENAME
fi

# Back up the public/private-files directories.
for public_or_private_files in public-files private-files; do

  # Switches to pass into the rsync command.
  rsync_options=""

  # If we have a reference directory, use it with the '--link-dest' option for rsync,
  # to create hard-linked copies of the files rather than full copies.
  if [ -n "$MOST_RECENT_BACKUP_DIR" ]; then
    rsync_options="--link-dest=$MOST_RECENT_BACKUP_DIR/$public_or_private_files"
  fi

  # - set up Source Dir, and
  # - exclude directories with unneeded (cached, derived) files.
  if [[ $public_or_private_files == "private-files" ]]; then
    SOURCE_DIR=$PRIVATE_FILES_PATH
    rsync_options="$rsync_options --exclude=styles"
  else
    SOURCE_DIR=$PUBLIC_FILES_PATH
    rsync_options="$rsync_options --exclude=styles --exclude=css --exclude=js --exclude=php"
  fi

  # Set up directory to copy into.
  DEST_DIR=$THIS_BACKUP_DIR/$public_or_private_files
  echo "Creating directory $DEST_DIR"
  mkdir -p $DEST_DIR

  # "Copy" the files to the new backup directory.
  #  Note that, to save disk-space, we use the "--link-dest" switch.
  #  With it, rsync will use hard-links for any/all identical files
  #  that already exist in the reference directory.
  echo "rsync-ing $public_or_private_files, with:"
  echo "rsync -a $rsync_options  $SOURCE_DIR/  $DEST_DIR/"
  rsync -a $rsync_options  $SOURCE_DIR/  $DEST_DIR/

done

#
#
# End of the primary, 'daily' backup
#
####


####
#
# Weekly/Monthly backups (of backups), setup...
#

# Use 'basic calculator' to support floating-point math.
FLOATING_POINT_SUPPORT="bc -l"

# Find weekly and monthly latest-backup.
#   Check for "UTC" to allow any other files to be ignored.
# ("LB" = latest backup)
WEEKLY_LB=$( ls -dt1  $WEEKLY_BACKUPS_DIR/*.UTC.* | head -n1 )
MONTHLY_LB=$(ls -dt1 $MONTHLY_BACKUPS_DIR/*.UTC.* | head -n1 )

# Calculate ages in days, by getting seconds-since-epoch for the file, and comparing with seconds-since-epoch for right now.
if [ -z $WEEKLY_LB ]; then
  # No weekly backups yet. Set it high, to make sure we get a new backup.
  AGE_OF_WEEKLY_LB_IN_DAYS=5000
else
  AGE_OF_WEEKLY_LB_IN_DAYS=$($FLOATING_POINT_SUPPORT <<< "($(date +%s) - $(date -r $WEEKLY_LB +%s))/24/60/60" )
fi

if [ -z $MONTHLY_LB ]; then
  # No monthly backups yet. Set it high, to make sure we get a new backup.
  AGE_OF_MONTHLY_LB_IN_DAYS=5000   # To make sure we get a backup.
else
  AGE_OF_MONTHLY_LB_IN_DAYS=$($FLOATING_POINT_SUPPORT <<< "($(date +%s) - $(date -r $MONTHLY_LB +%s))/24/60/60" )
fi

# Set up timezone, for use with 'date' command.
#   Note that technically it changes to "UTC+7" during daylight savings, but
#   we've coded this below to not care about that one hour.
#   (The lean Alpine linux seems to not support "America/Vancouver" type of timezones.)
export TZ="UTC+8"


#
# Weekly backup
#

# Week-days elapsed, right now. (aka 'floating point day-of-the-week')
#   0.0  = midnight Monday morning
#   0.5  = Monday noon
#   1.75 = Tues 6pm
#      etc.
WD_ELAPSED=$($FLOATING_POINT_SUPPORT <<< "$(date +%u)-1 + $(date +%H)/24")

# Do a weekly backup if
#   * it's near the end of the week (Friday evening midnight), OR
#   * (for some reason) there hasn't been a weekly backup for over a week.

echo "(Days of work-week that have elapsed: '$WD_ELAPSED'. We do a  weekly backup at ~5.0)"
echo "(Most-recent weekly backup is from $AGE_OF_WEEKLY_LB_IN_DAYS days ago.)"

REQUIREMENT="( $WD_ELAPSED >= 4.75  &&  $WD_ELAPSED <= 5.25)  ||  $AGE_OF_WEEKLY_LB_IN_DAYS >= 7"
if [[ $($FLOATING_POINT_SUPPORT <<< $REQUIREMENT) -eq 1 ]]; then
  echo "Doing a weekly backup!"

  # Make sure the weekly backups dir exists.
  mkdir -p $WEEKLY_BACKUPS_DIR

  # "Copy" (using hard-links) latest daily backup that we just made, into the 'weekly' directory.
  echo "Cloning '$THIS_BACKUP_DIR' into '$WEEKLY_BACKUPS_DIR'."
  cp --recursive --link  $THIS_BACKUP_DIR  $WEEKLY_BACKUPS_DIR

else
  echo "No need for a weekly backup."

fi


#
# Monthly backup
#

# Day of month right now.
DAY_OF_MONTH_NOW=$(date +%d)

# Do a monthly backup if
#   * it's the beginning of the month and the latest monthly backup is at least a week old, OR
#   * (for some reason) there hasn't been a monthly backup for over a month.
REQUIREMENT="($DAY_OF_MONTH_NOW <= 7  &&  $AGE_OF_MONTHLY_LB_IN_DAYS > 7)  ||  $AGE_OF_MONTHLY_LB_IN_DAYS > 31"
if [ $($FLOATING_POINT_SUPPORT <<< $REQUIREMENT) -eq 1 ]; then
  echo "Doing a monthly backup!"

  # Make sure the monthly backups dir exists.
  mkdir -p $MONTHLY_BACKUPS_DIR

  # "Copy" (using hard-links) latest daily backup that we just made, into the 'monthly' directory.
  echo "Cloning '$THIS_BACKUP_DIR' into '$MONTHLY_BACKUPS_DIR'."
  cp --recursive --link  $THIS_BACKUP_DIR  $MONTHLY_BACKUPS_DIR

else
  echo "No need for a monthly backup."

fi



echo
echo "Backups complete."



# Function to delete old backups
#
# For each backup, we delete its whole directory, including:
#      - DB dump file.
#      - public files
#      - private files

prune_old_backups () {

  # Which sub-directory of backups to prune: weekly, daily, etc.
  PERIODICITY=$1
  if ! [[ $PERIODICITY = @(daily|weekly|monthly) ]]; then
      echo "'$PERIODICITY' has to be daily, weekly or monthly!"
      return 1;
  fi

  DAYS_TO_KEEP=$2

  BACKUPS_TO_PRUNE="$BACKUPS_DIR/$PERIODICITY"

  echo "Looking in the $BACKUPS_TO_PRUNE directory for any $PERIODICITY backups"
  echo "  that are older than $DAYS_TO_KEEP days old."
  echo
  echo "  ... The following will be deleted:"
  find  $BACKUPS_TO_PRUNE  -maxdepth 1  -mtime +$DAYS_TO_KEEP
  echo "  ... (End of deletion list.)"

  # Do the deletion:
  find  $BACKUPS_TO_PRUNE  -maxdepth 1  -mtime +$DAYS_TO_KEEP  -exec rm -rf {} \;

  echo "Pruning complete."
  sleep 3
}

prune_old_backups daily    14
prune_old_backups weekly   62
prune_old_backups monthly 367


echo "(done)"
