#!/bin/bash

# Delete old backups
#
# For each backup, we delete its whole directory, including:
#      - DB dump file.
#      - public files
#      - private files

# Which sub-directory of backups to prune: weekly, daily, etc.
PERIODICITY=$1
if ! [[ $PERIODICITY = @(daily|weekly|monthly) ]]; then
    echo "'$PERIODICITY' has to be daily, weekly or monthly!"
    return 1;
fi

DAYS_TO_KEEP=$2

BACKUPS_ROOT="/var/www/backups"
BACKUPS_TO_PRUNE="$BACKUPS_ROOT/$PERIODICITY"

echo "Looking in the $BACKUPS_TO_PRUNE directory for any $PERIODICITY backups"
echo "  that are older than $DAYS_TO_KEEP days old."
echo
echo "  ... The following will be deleted:"
find  $BACKUPS_TO_PRUNE  -maxdepth 1  -mtime +$DAYS_TO_KEEP
echo "  ... (End of deletion list.)"

# Do the deletion:
find  $BACKUPS_TO_PRUNE  -maxdepth 1  -mtime +$DAYS_TO_KEEP  -exec rm -rf {} \;

echo "Pruning complete."
