#!/bin/sh

# Set up
DIR_DAILY="/app/backups/daily" ;
DIR_WEEKLY="/app/backups/weekly"

# Find the directory that contains the latest daily backup.
LATEST_BACKUP=$(ls $DIR_DAILY -t1|head -n1)

# "Copy" (using hard-links) this latest backup into the 'weekly' directory.
echo "Cloning '$DIR_DAILY/$LATEST_BACKUP' into '$DIR_WEEKLY/$LATEST_BACKUP'."
cp --recursive --link  $DIR_DAILY/$LATEST_BACKUP  $DIR_WEEKLY/$LATEST_BACKUP

echo "Weekly clone of a backup is complete."