<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_menu_local_tasks_alter().
 */
function bcbb_auth_menu_local_tasks_alter(array &$data, string $route_name, RefinableCacheableDependencyInterface &$cacheability): void {
  switch ($route_name) {
    case 'user.login':
      // Only act if openid_connect is installed.
      if (!\Drupal::service('module_handler')->moduleExists('openid_connect')) {
        break;
      }
      // Hide password reset tab unless 'showcore' query param is set.
      $showcore = \Drupal::request()->get('showcore');
      if (is_null($showcore)) {
        unset($data['tabs'][0]['user.pass']);
      }
      // Include 'showcore' query param in cache context.
      $cacheability->addCacheContexts([
        'url.query_args:showcore',
      ]);
      break;
  }
}

/**
 * Implements template_preprocess_block().
 */
function bcbb_auth_preprocess_block(array &$variables): void {
  // Only act if openid_connect is installed.
  if (!\Drupal::service('module_handler')->moduleExists('openid_connect')) {
    return;
  }

  // Remove link to password reset from login block.
  if ($variables['plugin_id'] === 'user_login_block') {
    unset($variables['content']['user_links']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bcbb_auth_form_node_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  $node = $form_state->getFormObject()->getEntity();

  // Use display name for author on node edit pages.
  // @todo Remove when fixed via this issue:
  // https://www.drupal.org/project/drupal/issues/3183509
  if ($node instanceof NodeInterface  && isset($form['meta']['author']['#markup'])) {
    $form['meta']['author']['#markup'] = $node->getOwner()->getDisplayName();
  }
}
