field.formatter.settings.data_set_column_name:
  type: mapping
  label: 'Data set column name settings'
  mapping:
    display_inline:
      type: boolean
      label: 'Display inline'

page_manager.block_plugin.bc_dc_edit_button:
  type: block.settings.[id]
  mapping:
    region:
      type: string
      label: 'Region'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: string
      label: 'UUID'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        - type: string
    query_param:
      type: string
      label: 'Query param'
