bc_dc.settings:
  type: config_object
  label: 'BC Data Catalogue Module settings'
  mapping:
    data_set_review_period_alert:
      type: integer
      label: 'Review period alert'
    review_needed_message:
      type: label
      label: 'Review needed message'
    review_overdue_message:
      type: label
      label: 'Review overdue message'
    info_schedule_pre_title:
      type: label
      label: 'Information schedule term pre-title'

block.settings.bc_dc_edit_button:
  type: block_settings
  mapping:
    region:
      type: string
      label: 'Region'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: string
      label: 'UUID'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        - type: string
    query_param:
      type: string
      label: 'Query param'

field.formatter.settings.data_set_facet_search_link:
  type: mapping
  label: 'Data set facet search link settings'
  mapping:
    format_as_list:
      type: boolean
      label: 'Format as list'
