NEWBB: This is not a complete DDEV config file, but only a couple essential parts for basebuild.
NEWBB2: Merge these in, and delete these comments.

database:
    type: postgres

web_environment:
    # newbb: To set the ACTUAL values for these environment variables,
    # override 'web_environment' in a ".ddev/config.local.yaml" or ".ddev/config.yourname.local.yaml" file.
    # "Local" yaml files are git-ignored by default by DDEV's own .gitignore file.
    # See https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#extending-configyaml-with-custom-configyaml-files
    - SHIELD_USER=newbb
    - SHIELD_PASS=newbb
    - SSO_CLIENT_ID=newbb
    - SSO_CLIENT_SECRET=newbb
    - SSO_KEYCLOAK_BASE=newbb
    - SOLR_PASSWORD=newbb
