#!/bin/bash

PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin
CRON=core-cron
DRUPAL=/var/www/html
DRUSH=`which drush`

if [ ! -f $DRUSH ]
then
  echo `date`" - Drush not found: Skipping Cron"
  exit
fi

# Run the cron.
echo `date`" - Drush: Running Cron"
$DRUSH --root=$DRUPAL $CRON
