name: Cleanup artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  CONTAINER_REPO: ${{ vars.CONTAINER_REPO }}
  ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}
  CONTAINER_REGISTRY_USERNAME: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

jobs:
  cleanup:
    runs-on: ubuntu-22.04

    steps:
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ env.ARTIFACTORY_URL }}
          JF_USER: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          JF_PASSWORD: ${{ env.CONTAINER_REGISTRY_PASSWORD }}

      - run: jf --version

      - name: Check JFrog Connection
        id: check_connection
        run: |
          response=$(jf rt ping)
          echo "Response: $response"
          echo "STATUS=$response" >> $GITHUB_ENV

      - name : Checkout code
        uses: actions/checkout@v4

      - name: Search and delete old artifacts
        if: ${{ env.STATUS == 'OK' }}
        run: |
          n=35
          echo "Retaining $n images"
          jf rt s --spec .github/workflows/artifactory-cleanup.search-spec.json --offset=$n --sort-by="modified" --sort-order=desc | jq .[].path | jq 'sub("/manifest.json"; "")' > jfrog_artifacts.txt

          total_images=$(wc -l < jfrog_artifacts.txt)
            echo "Total Images: $total_images"
            if [ "$total_images" -gt 0 ]; then
              while IFS= read -r artifact; do
                artifact="${artifact%\$}"
                echo "Attempting to delete: $artifact"
                command="jf rt del $artifact --quiet=true"
                echo "Command to be executed: $command"
                response=$(eval "$command")

                # Check for failure in the response
                if echo "$response" | jq -e '.status != "success"' > /dev/null; then
                  echo "Failed to delete $artifact. Response: $response"
                else
                  echo "Successfully deleted $artifact."
                fi
              done < jfrog_artifacts.txt
            else
               echo "No images to delete in the repository"
            fi
          rm -f jfrog_artifacts.txt
          echo "Successfully cleaned up temporary files."
