name: Build
on:
  pull_request:
  push:
    branches:
      - 1.0.x
    paths-ignore:
    - 'README.md'

env:
  COMPOSER_MEMORY_LIMIT: -1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master

    - name: Build out the Drupal infrastructure
      run: |
<<<<<<< HEAD
        export DB_TYPE=mysql  # NEWBB -confirm database type
=======
        export DB_TYPE=mysql
>>>>>>> a591caff3... Switch back to DB_TYPE=mysql for GitHub Actions in Build and Dev
        export DB_PORT=3306

        # # We used to 'git clone' to get the '/docker' directory loaded,
        # # but now we have made that code part of this repo. Commenting it out:
        # git clone --branch 10.2.x-php8.2 https://github.com/drupalwxt/docker-scaffold.git docker

        make build
        docker compose -f docker-compose.ci.yml up -d
        docker ps -a

    - name: Scan PHP-FPM image for vulnerabilities
      uses: aquasecurity/trivy-action@v0.29.0
      with:
        image-ref: '${{ vars.CONTAINER_IMAGE_NAME }}-web:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Scan Nginx image for vulnerabilities
      uses: aquasecurity/trivy-action@v0.29.0
      with:
        image-ref: '${{ vars.CONTAINER_IMAGE_NAME }}-nginx:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'
