name: Deploy to Development

on:
  push:
    tags:
    - '*'
    - '!*-TEST'
    - '!*-PROD'
    paths-ignore:
    - 'README.md'

env:
  COMPOSER_MEMORY_LIMIT: -1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master

    - name: Export github reference var
      run: |
        echo "TENANT_GITOPS_REPO=${{ vars.TENANT_GITOPS_REPO }}" >> $GITHUB_ENV
        echo "DRUPAL_REPO_TAG_TO_DEPLOY=$GITHUB_REF_NAME" >> $GITHUB_ENV
        echo "DRUPAL_REPO_AUTHOR_INFO=$(git show -s --format='%an, on %ad' $GITHUB_SHA)" >> $GITHUB_ENV
        echo "DRUPAL_REPO_COMMITTER=$(git show -s --format='%cn' $GITHUB_SHA)" >> $GITHUB_ENV
        echo "DRUPAL_REPO_COMMIT_DATETIME=$(git show -s --format='%cd' --date=format:'%Y-%m-%d (%a) %H:%M' $GITHUB_SHA)" >> $GITHUB_ENV
        echo "DRUPAL_REPO_COMMIT_MESSAGE=$(git show -s --format="%B" $GITHUB_SHA)" >> $GITHUB_ENV

    - name: Build out the Drupal infrastructure
      run: |
        export DB_TYPE=mysql
        export DB_PORT=3306

        # # We used to 'git clone' to get the '/docker' directory loaded,
        # # but now we have made that code part of this repo. Commenting it out:
        # git clone --branch 10.2.x-php8.2 https://github.com/drupalwxt/docker-scaffold.git docker

        make build
        docker compose -f docker-compose.ci.yml up -d
        docker ps -a

    - name: Scan PHP-FPM image for vulnerabilities
      if: ${{ ( startsWith(github.event.ref, 'refs/tags/') && (endsWith(github.event.ref, '.t') || endsWith(github.event.ref, '-t') )) }}
      uses: aquasecurity/trivy-action@v0.35.0
      with:
        image-ref: '${{ vars.CONTAINER_IMAGE_NAME }}-web:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Scan Nginx image for vulnerabilities
      if: ${{ ( startsWith(github.event.ref, 'refs/tags/') && (endsWith(github.event.ref, '.t') || endsWith(github.event.ref, '-t') )) }}
      uses: aquasecurity/trivy-action@v0.35.0
      with:
        image-ref: '${{ vars.CONTAINER_IMAGE_NAME }}-nginx:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Login to Container Registry 🐸
      uses: docker/login-action@v2
      with:
        registry: ${{ vars.CONTAINER_REGISTRY }}
        username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push PHP-FPM 🐳
      run: |
        # Will end up looking something like this:
        # docker tag fin-exec-support-system-web:latest artifacts.developer.gov.bc.ca/eeba-ess-docker-local/fin-exec-support-system:test-6a-f
        docker tag ${{ vars.CONTAINER_IMAGE_NAME }}-web:latest ${{ vars.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ env.DRUPAL_REPO_TAG_TO_DEPLOY }}
        docker push ${{ vars.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ env.DRUPAL_REPO_TAG_TO_DEPLOY }}

    - name: Build and push Nginx 🐳
      run: |
        # Will end up looking something like this:
        # docker tag fin-exec-support-system-nginx:latest artifacts.developer.gov.bc.ca/eeba-ess-docker-local/fin-exec-support-system-nginx:test-6a-f
        docker tag ${{ vars.CONTAINER_IMAGE_NAME }}-nginx:latest ${{ vars.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_IMAGE_NAME }}-nginx:${{ env.DRUPAL_REPO_TAG_TO_DEPLOY }}
        docker push ${{ vars.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_IMAGE_NAME }}-nginx:${{ env.DRUPAL_REPO_TAG_TO_DEPLOY }}

    - name: Checkout Tenant GitOps Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ vars.TENANT_GITOPS_REPO }}
        path: tenant-gitops
        ssh-key: ${{ secrets.TENANT_GITOPS_DEPLOY_KEY }}
        persist-credentials: true

    - name: Update the Dev and Test values-application yaml files with this deployment's tag 
      uses: mikefarah/yq@v4.34.1
      with:
        cmd: |
          yq -i '.drupal.tag = strenv(DRUPAL_REPO_TAG_TO_DEPLOY) |
                 .nginx.tag  = strenv(DRUPAL_REPO_TAG_TO_DEPLOY)' tenant-gitops/helm-drupal/charts/drupal/values-application-dev.yaml
          yq -i '.drupal.tag = strenv(DRUPAL_REPO_TAG_TO_DEPLOY) |
                 .nginx.tag  = strenv(DRUPAL_REPO_TAG_TO_DEPLOY)' tenant-gitops/helm-drupal/charts/drupal/values-application-test.yaml

    - name: Commit this change to git
      run: |
        cd tenant-gitops
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Update DEV and TEST servers to '${{ env.DRUPAL_REPO_TAG_TO_DEPLOY }}'."

    - name: Push this commit back up to GitHub
      uses: ad-m/github-push-action@master
      with:
        ssh: true
        branch: main
        directory: tenant-gitops
        repository: ${{ vars.TENANT_GITOPS_REPO }}
