name: Deploy to Development

on:
  push:
    tags:
    - '*'
    paths-ignore:
    - 'README.md'

env:
  COMPOSER_MEMORY_LIMIT: -1
  CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
  CONTAINER_REGISTRY_USERNAME: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master

    - name: Export github reference var
      run: echo "GITHUB_REFERENCE=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

    - name: Update application version
      uses: mikefarah/yq@v4.34.1
      with:
        cmd: |
          yq eval '.version = strenv(GITHUB_REFERENCE)' -i html/modules/custom/newbbproj_common/newbbproj_common.info.yml

    - name: Build out the Drupal infrastructure
      run: |
        export DB_TYPE=mysql  # NEWBB -confirm database type
        export DB_PORT=3306

        # # We used to 'git clone' to get the '/docker' directory loaded,
        # # but now we have made that code part of this repo. Commenting it out:
        # git clone --branch 10.2.x-php8.2 https://github.com/drupalwxt/docker-scaffold.git docker

        make build
        docker compose -f docker-compose.ci.yml up -d
        docker ps -a
        sleep 10

    - name: Run installation
      run: |
        export DB_TYPE=mysql  # NEWBB -confirm database type
        export DB_PORT=3306
        make drupal_install

    - name: Run tests
      if: ${{ ! ( startsWith(github.event.ref, 'refs/tags/') && (endsWith(github.event.ref, '.f') || endsWith(github.event.ref, '-f') )) }}
      run: |
        export DB_TYPE=mysql  # NEWBB -confirm database type
        export DB_PORT=3306
        ./docker/bin/phpcs --standard=/var/www/html/core/phpcs.xml \
            --extensions=php,module,inc,install,test,profile,theme \
            --report=full \
            --colors \
            /var/www/html/modules/contrib/NEWBB_module_to_test \
            /var/www/html/modules/custom/NEWBB_other_module_to_test \
            /var/www/html/modules/custom/NEWBB_another_module_to_test \

    - name: Scan PHP-FPM image for vulnerabilities
      if: ${{ ! ( startsWith(github.event.ref, 'refs/tags/') && (endsWith(github.event.ref, '.f') || endsWith(github.event.ref, '-f') )) }}
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: '${{ vars.CONTAINER_IMAGE_NAME }}-web:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Scan Nginx image for vulnerabilities
      if: ${{ ! ( startsWith(github.event.ref, 'refs/tags/') && (endsWith(github.event.ref, '.f') || endsWith(github.event.ref, '-f') )) }}
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: '${{ vars.CONTAINER_IMAGE_NAME }}-nginx:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Login to Container Registry 🐸
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push PHP-FPM 🐳
      run: |
        # Will end up looking something like this:
        # docker tag fin-exec-support-system-web:latest artifacts.developer.gov.bc.ca/eeba-ess-docker-local/fin-exec-support-system:test-6a-f
        docker tag ${{ vars.CONTAINER_IMAGE_NAME }}-web:latest ${{ env.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ env.GITHUB_REFERENCE }}
        docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ env.GITHUB_REFERENCE }}

    - name: Build and push Nginx 🐳
      run: |
        # Will end up looking something like this:
        # docker tag fin-exec-support-system-nginx:latest artifacts.developer.gov.bc.ca/eeba-ess-docker-local/fin-exec-support-system-nginx:test-6a-f
        docker tag ${{ vars.CONTAINER_IMAGE_NAME }}-nginx:latest ${{ env.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_IMAGE_NAME }}-nginx:${{ env.GITHUB_REFERENCE }}
        docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_IMAGE_NAME }}-nginx:${{ env.GITHUB_REFERENCE }}

    - name: Checkout Tenant GitOps Repo
      uses: actions/checkout@v4
      with:
        repository: bcgov-c/tenant-gitops-newbblicenseplate
        path: tenant-gitops
        ssh-key: ${{ secrets.ARGO_OPENSHIFT_DEPLOYMENT_PIPELINE_SSH_KEY }}
        persist-credentials: true

    - name: Update Argo CD
      uses: mikefarah/yq@v4.34.1
      with:
        cmd: |
          yq -i '.drupal.tag = strenv(GITHUB_REFERENCE) |
                 .nginx.tag = strenv(GITHUB_REFERENCE) ' tenant-gitops/helm-drupal/charts/drupal/values-application-dev.yaml

    - name: Commit files
      run: |
        cd tenant-gitops
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "feat(helm): Update container images to ${{ env.GITHUB_REFERENCE }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        ssh: true
        branch: main
        directory: tenant-gitops
        repository: bcgov-c/tenant-gitops-newbblicenseplate
