on: [push]


jobs:
  get_secrets:
    name: GetSecrets
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Output secrets
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
        CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        CONTAINER_REPO: ${{ secrets.CONTAINER_REPO }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SSH_KEY: ${{ secrets.SSH_KEY }}

      run: |
        echo 'ARTIFACTORY_URL'
        echo $ARTIFACTORY_URL | sed 's/./& /g'
        echo $ARTIFACTORY_URL | xxd -ps

        echo 'CONTAINER_REGISTRY'
        echo $CONTAINER_REGISTRY | sed 's/./& /g'
        echo $CONTAINER_REGISTRY | xxd -ps

        echo 'CONTAINER_REGISTRY_PASSWORD'
        echo $CONTAINER_REGISTRY_PASSWORD | sed 's/./& /g'
        echo $CONTAINER_REGISTRY_PASSWORD | xxd -ps

        echo 'CONTAINER_REGISTRY_USERNAME'
        echo $CONTAINER_REGISTRY_USERNAME | sed 's/./& /g'
        echo $CONTAINER_REGISTRY_USERNAME | xxd -ps

        echo 'CONTAINER_REPO'
        echo $CONTAINER_REPO | sed 's/./& /g'
        echo $CONTAINER_REPO | xxd -ps

        echo 'GH_TOKEN'
        echo $GH_TOKEN | sed 's/./& /g'
        echo $GH_TOKEN | xxd -ps

        echo 'SSH_KEY'
        echo $SSH_KEY | sed 's/./& /g'
        echo $SSH_KEY | xxd -ps
