<?php

/**
 * @file
 * Contains op_ext_search.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function op_ext_search_theme(array $existing, string $type, string $theme, string $path): array {
  return [
    'custom_search_api_block' => [
      'variables' => [
        'search' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function op_ext_search_theme_suggestions_views_view_alter(array &$suggestions, array $variables): void {
  if ($variables['view']->id() == 'site_search') {
    $suggestions[] = $variables['theme_hook_original'] . '__site_search';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function op_ext_search_form_wxt_search_api_block_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();

  $form['search_api_fulltext']['#placeholder'] = t('Search website');
  $form['#action'] = $lang == 'en' ? '/en/search/site' : '/fr/recherche/site';
}

/**
 * Implements hook_module_implements_alter().
 */
function op_ext_search_module_implements_alter(array &$implementations, string $hook): void {
  if ($hook == 'form_wxt_search_api_block_form_alter') {
    // Unset op_ext_search hook if gcext implements it,
    // this allows us to override per project if needed.
    if (isset($implementations['gcext'])) {
      unset($implementations['op_ext_search']);
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function op_ext_search_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  // Hide label on search block on site search page.
  $view = $form_state->getStorage('view');

  if ($view['view']->id() == 'site_search') {
    $form['keys']['#title_display'] = 'invisible';
  }

  $form['search_api_fulltext']['#title'] = t('Search');

  $form['search_api_fulltext']['#label_attributes'] = [
    'class' => ['sr-only'],
  ];
}
