<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Link;

/**
 * Implements hook_preprocess_HOOK() for block--facets-summary.html.twig.
 */
function op_ext_search_preprocess_block__facets_summary(array &$variables): void {
  // Do not show the block label when there are no facets selected.
  if (!$variables['content']['#items']) {
    $variables['label'] = NULL;
  }
}

/**
 * Implements hook_preprocess_HOOK() for node--data-set--full.html.twig.
 */
function op_ext_search_preprocess_node__data_set__full(array &$variables): void {
  // Author of this node.
  $author = $variables['node']->getRevisionUser();
  // Query string for searching for the author as a facet.
  $options = [
    'query' => [
      'f' => [
        'author_id:' . $author->id(),
      ],
    ],
  ];
  // Make link to search for this author available to template.
  $variables['author_link'] = Link::createFromRoute($author->getDisplayName(), 'page_manager.page_view_site_search_site_search-panels_variant-0', [], $options);
}
